### DISCUSSION TITLE
安装 Docker-部署 Qanything/Dify 项目 | /project/docker/

### DISCUSSION THREAD

**Discussion by giscus** [earfanfan/yuanfan#657] [Announcements]
https://yuanfan.rbind.io/project/docker/

**Comment by hongtaoh** [comment]
Docker 我现在也不会。因为我用不到。我感觉很难啊，都不知道它是干嘛的。我这个 cs phd 读的。。

**Reply by earfanfan** [reply]
喂喂，年轻人，你刚刚是不是把什么东西扔进河里啦？砸到本河神的头了啊，请问你扔的是这个金自信、银自信，还是铜自信呢？

话又说回来，郝糊涂，你最近是心灵受到伤害了么，是不是受到了什么挫折或打击？我记得好多年前湘云给我安利 Docker 的时候我也觉得超级难，根本不可能学会，等到我自己在服务器上折腾过以后才终于慢慢弄懂了一些。我觉得等你将来可以在服务器上瞎折腾 Docker 的时候，自然而然就会学会了。快把你的自信捡起来吧。

如果要问 Docker 是干嘛的，你可以戳[这里](https://docker-practice.github.io/zh-cn/introduction/what.html)，或者让 AI 给你介绍一下，或者去找湘云问问也行。

**Comment by yihui** [comment]
> 而 yaml 语法简单、非常易读，没有函数全是参数名和参数值，对人类十分友好

我的天，YAML 在我眼里简直可以说是对人类最不友好的配置语言……它有友好的一部分，但那只是它的冰山一小小小角；欲观摩整座冰山，请先深呼吸再戳开：https://yaml.org/spec/1.2.2/ 这特么哪是人类能理解的语言。

我在 [litedown 文档中](https://yihui.org/litedown/#sec:yaml-syntax)吐槽了 YAML 之复杂与奇葩，不知读者是否能理解那个关于挪威人的笑话。我把冰山一小小小角抠了出来，给它取了个新名字叫 TAML（TRACY Ain't Markup Language）。

**Reply by earfanfan** [reply]
>请先深呼吸再戳开

我没有受过你受过的苦，所以戳开撒感觉也没有。另外，其实我没把 YAML 当做一种可以完整表达内容的语言看待。我记得老早以前改博客文件的时候不仅有 YAML，好像还见过 TOML。但我只记得它俩很相似。

所以你吐槽的是撒，在你写的文档里按照 YAML 为关键词可以搜索出来47项。

我之前觉得 YAML 友好，是因为当我想要修改的时候见到的是下面酱紫的，看起来确实很清晰，分门别类摆放的很好。

```
services:
  elasticsearch:
    container_name: es-container-local
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    user: root
    privileged: true
    ports:
      - "9210:9200"
    restart: on-failure
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
```

直到今天，我要改另一个项目的 YAML 文件，一打开发现文件行数无限长，开头全是下面酱紫的。这种的我就感觉心塞了，根本没法翻到想改的东西在哪里。

```
x-shared-env: &shared-api-worker-env
  CONSOLE_API_URL: ${CONSOLE_API_URL:-}
  CONSOLE_WEB_URL: ${CONSOLE_WEB_URL:-}
  SERVICE_API_URL: ${SERVICE_API_URL:-}
  APP_API_URL: ${APP_API_URL:-}
  APP_WEB_URL: ${APP_WEB_URL:-}
  FILES_URL: ${FILES_URL:-}
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  LOG_FILE: ${LOG_FILE:-/app/logs/server.log}
  LOG_FILE_MAX_SIZE: ${LOG_FILE_MAX_SIZE:-20}
  LOG_FILE_BACKUP_COUNT: ${LOG_FILE_BACKUP_COUNT:-5}
  LOG_DATEFORMAT: ${LOG_DATEFORMAT:-%Y-%m-%d %H:%M:%S}
  LOG_TZ: ${LOG_TZ:-UTC}
  DEBUG: ${DEBUG:-false}
```
